### PR TITLE
@Scaffold annotation for Controllers and Services

### PR DESCRIPTION
**Pull request by codeconsole**
Adds support for the annotation`@Scaffold` which provides an alternative to the `static scaffold = Domain` approach. 
```groovy
@Scaffold(domain = User)
class UserController {}
```

It also empowers the developer to use their own base controller instead of being forced to use `RestController` which could be very limiting.  `RestController` does not encapsulate all necessary business logic and is completely divergent from the Service MVC model that is generated by this plugin.  With this annotation, developers can now use an extended RestController to fit their needs, or create an entirely different generic controller that is not related at all to RestController and more closely matches the type of controller that is generated by this plugin.

```groovy
@Scaffold(RestfulServiceController)
class UserController {
    static scaffold = User
}
```

```groovy
@Scaffold(value = RestfulServiceController, domain = User)
class UserController {}
```

can now be written as this
```groovy
@Scaffold(RestfulServiceController<User>)
class UserController {}
```

Introduce `@Scaffold`  Service support

It is very powerful if you have common business logic shared across multiple or all services and use a service layer. It works similar to how scaffold controllers work.  You have a super class that you define (such are `RestfulContoller` for scaffold controllers) and then any Services with the annotation get that super class injected.  

Now all I have to do is have define a Service with the annotation and all those methods become implemented. Unlike `@Service`, I can override individual methods and call super
```groovy
@Scaffold(GormService<User>)
class UserService {

    User save(User user) {
         user.modified = new Date()
         super.save(user)
    }
}
```

Introduced 2 new classes:
`RestfulServiceController` - which is the same as RestfulContoller, but makes all datasource calls to the respective Service. 
`GormService` - which scaffolds a generic service similar to `Service.groovy` but instead of using an interface with `@Service`, it sets a superclass where methods can be overridden and extended.  You can also define any class as your base service.  

By using `@Scaffold` you can now do things for specific needs of groups of domain objects.

```groovy
@Scaffold<SecuredAdminController<User> // adds @Secured('ROLE_ADMIN') to all methods
@Scaffold<domain = User, readOnly = true> // puts RestfulContoller in readOnly mode
@Scaffold<CachingService<User> // uses Redis as a caching layer 
@Scaffold<SearchableService<User> // indexes changes to Elastic search
```
The possibilities are endless!

https://github.com/grails/scaffolding/issues/113

https://github.com/grails/scaffolding/pull/114

### CODE REVIEW

**Comment by matrei** [comment]
Looks awesome!

Is using:
```groovy
@ScaffoldService(GenericService<User>)
class UserService
{}
```
equivalent to:
```groovy
class UserService extends GenericService<User>
{}
```
It would be really nice if there were some tests showing that these new features work as intended.

**Comment by codeconsole** [comment]
> Looks awesome!
> 
> Is using:
> 
> ```groovy
> @ScaffoldService(GenericService<User>)
> class UserService
> {}
> ```
> 
> equivalent to:
> 
> ```groovy
> class UserService extends GenericService<User>
> {}
> ```
yes, it is equivalent more or less. It works the same way how `static scaffold = User` works where `UserController` ends up extending `RestController`

The main work that it does is by setting the domain class in the constructor. If you used class extension, you would have to create a constructor for every service..

```groovy
class UserService extends GenericService<User> {
     UserService() {
          super(User, false)
     }
}
```
would more or less be the equivalent.

I am trying to decide whether or not to ditch the `readOnly` property.   If it is going to be used, it should be added to the annotation.   I am thinking about adding readOnly to the `@ScaffoldController` annotation

**Comment by matrei** [comment]
> If you used class extension, you would have to create a constructor for every service.

I don't follow, why would I have to create a constructor (if my GenericService has a no-args constructor)?
What is the `false` value you are passing to the constructor in your example? `readOnly`?

**Comment by codeconsole** [comment]
> > If you used class extension, you would have to create a constructor for every service.
> 
> I don't follow, why would I have to create a constructor (if my GenericService has a no-args constructor)? 

If your GenericService<T> has a no-args constructor, how else would you resolve <T> as a User if you don't have a reference to T.class?


```groovy
class GenericService<T> {
    @Autowired DatastoreService datastore

    GenericService() {}

    T get(Serializable id) {
        // how else would you resolve T ???
    }
}
```

Doesn't `GenericService` need a reference to the class it is revolving?

```groovy
@ScaffoldService(GenericService<User>)
class UserService {}
```

vs

```groovy
class UserService extends GenericService<User> {
     UserService() {
          super(User, false)
     }
}
```

```groovy
class GenericService<T> {
    Class<T> resource
    String resourceName
    @Autowired DatastoreService datastore

    GenericService(Class<T> resource, boolean readOnly) {
        this.resource = resource
        this.readOnly = readOnly
    }

    T get(Serializable id) {
        T instance = resource.getDeclaredConstructor().newInstance()
        instance.properties << datastore.get(id)   
        instance
    }
```

> What is the false value you are passing to the constructor in your example? readOnly?

yes, readOnly.

**Comment by matrei** [comment]
> If your GenericService has a no-args constructor, how else would you resolve as a User if you don't have a reference to T.class?

Can't you get the implementation class with `getClass()`:
```groovy
T get(Serializable id) {
    T instance = (T) getClass().getDeclaredConstructor().newInstance()
    instance.properties << datastore.get(id)
    instance
}
```

**Comment by codeconsole** [comment]
> > If your GenericService has a no-args constructor, how else would you resolve as a User if you don't have a reference to T.class?
> 
> Can't you get the implementation class with `getClass()`:
> 
> ```groovy
> T get(Serializable id) {
>     T instance = (T) getClass().getDeclaredConstructor().newInstance()
>     instance.properties << datastore.get(id)
>     instance
> }
> ```

Isn't the whole point to instantiate and return a`User` instance?   Wouldn't your code `getClass().getDeclaredConstructor().newInstance()`  just create another `UserService`??

**Comment by matrei** [comment]
> Isn't the whole point to instantiate and return aUser instance? Wouldn't your code getClass().getDeclaredConstructor().newInstance() just create another UserService??

Yes, you are correct! Thinking mistake by me :smile: 
Then, I see the use of the `@ScaffoldService` annotation.

**Comment by codeconsole** [comment]
> > Isn't the whole point to instantiate and return aUser instance? Wouldn't your code getClass().getDeclaredConstructor().newInstance() just create another UserService??
> 
> Yes, you are correct! Thinking mistake by me 😄 Then, I see the use of the `@ScaffoldService` annotation.

All good.  You almost had be believing you when I read your code at 2am lol

**Comment by codeconsole** [comment]
@matrei @jamesfredley  I am getting close to merging this.   One last thing we could consider:
Since `@ScaffoldController` and `@ScaffoldService` are identical, should we use the same annotation `@Scaffold` for both controllers and services?

They both do the same thing:  
1. define a super class.  
2. define a domain class.  
3. define readOnly mode.

```groovy
@Scaffold(GenericService<User>)
class UserService {}
```

```groovy
@Scaffold(RestfulController<User>)
class UserController {}
```

```groovy
@Scaffold(domain = Book)
class BookController {}
```

**Comment by matrei** [comment]
@codeconsole If it is technically feasible, I think a unified `@Scaffold` annotation sounds excellent.

Should we also deprecate (not remove), the usage of `static scaffold = Book`, to signal that the annotation is the new better way. `static scaffold = Book` is also not working on Services and could therefore cause confusion.

**Comment by jamesfredley** [comment]
`@Scaffold` would be ideal.  

And we will want to update https://github.com/grails/grails-doc/blob/6.2.x/src/en/guide/scaffolding.adoc

**Comment by codeconsole** [comment]
Provided default `GenericService` implementation that matches Service.groovy, but allows method overriding and calls to super:

```groovy
@Scaffold(domain = User)
class UserService {}

@Scaffold(domain = Book)
class BookService {
    Book save(Book book) {
         book.owner = request.user
         super.save(user)
    }
}

@Scaffold(domain = Car)
class CarService {}

@Scaffold(domain = Pet, readOnly = true)
class PetService {}

class BootStrap {
    CarrService carService
    PetService petService
    UserService userService
    BookService bookService

    def init = { servletContext ->
         User rainboyan = userService.save(new User(username:'rainboyan')
         Car porsche = carService.save(new Car(make:'Porsche',  model:'911', owner: rainboyan)
         Book grails = bookService.save(new Book(name:'Programming Grails')
         Pet cat = petService.save(new Pet(name: 'Garfield', owner: rainboyan) // exception throw because service is readOnly
    }
}
```

**Comment by codeconsole** [comment]
Created a version of RestfulController that utilizes services so that a complete implementation could be provided that uses a scaffolded service. 

```groovy
@Scaffold(RestfulServiceController<Book>)
class BookController {}
```

```groovy
@Scaffold(domain = Book)
class BookService {}
```

**Comment by matrei** [comment]
Could we compile `GenericService` statically if we narrow the type to `<T extends GormEntity>` and create an instance in the constructor for the `GormAllOperations` methods?

And don't we also have to manage the `readOnly` property for the `save` and `delete` methods, and also set `@Transactional` on those two methods?

```groovy
package grails.plugin.scaffolding

import grails.artefact.Artefact
import grails.gorm.api.GormAllOperations
import grails.gorm.transactions.ReadOnly
import grails.gorm.transactions.Transactional
import grails.util.GrailsNameUtils
import groovy.transform.CompileStatic

@Artefact("Service")
@ReadOnly
@CompileStatic
class GenericService<T extends GormEntity<T>> {

    GormAllOperations<T> resource
    String resourceName
    String resourceClassName
    boolean readOnly

    GenericService(Class<T> resourceClass, boolean readOnly) {
        this.resource = resourceClass.getDeclaredConstructor().newInstance() as GormAllOperations<T>
        this.readOnly = readOnly
        this.resourceClassName = resourceClass.simpleName
        this.resourceName = GrailsNameUtils.getPropertyName(resourceClass)
    }

    protected T queryForResource(Serializable id) {
        resource.get(id)
    }

    T get(Serializable id) {
        queryForResource(id)
    }

    List<T> list(Map args) {
        resource.list(args)
    }

    Long count() {
        resource.count()
    }

    @Transactional
    void delete(Serializable id) {
        if (readOnly) {
            return
        }
        resource.delete(queryForResource(id), [flush: true])
    }

    @Transactional
    T save(T instance) {
        if (readOnly) {
            return instance
        }
        resource.save(instance, [flush: true])
    }
}
```

**Comment by codeconsole** [comment]
> Could we compile `GenericService` statically if we narrow the type to `<T extends GormEntity>` and create an instance in the constructor for the `GormAllOperations` methods?
> 
> And don't we also have to manage the `readOnly` property for the `save` and `delete` methods, and also set `@Transactional` on those two methods?
> 

Sure, should we rename `GenericService` to something else? `GormService` or `GenericGormService` ?

**Comment by matrei** [comment]
> Sure, should we rename GenericService to something else? GormService or GenericGormService ?

Maybe `DefaultScaffoldService`

**Comment by codeconsole** [comment]
> > Sure, should we rename GenericService to something else? GormService or GenericGormService ?
> 
> Maybe `DefaultScaffoldService`

but is this the best name since it could also be utilized independently like RestfulController can?

**Review by jamesfredley — APPROVED** [review]
GormService is a unique name across the Grails codebase.  👍

Issue created for documentation update:  https://github.com/grails/grails-doc/issues/909

**Pull request merged**
