### PR TITLE
Update Fields plugin from 3.0.0.RC1 to 5.0.3

### PR DESCRIPTION
**Pull request by codeconsole**

### CODE REVIEW

**Comment by sbglasius** [comment]
If I could, I would approve this 👍🏻

**Comment by matrei** [comment]
I don't have access to this particular repo either, but if the checks pass, I would approve this.

Maybe I am missing something, but,, when trying to load this repo locally, I get `Could not find org.grails:grails-plugin-testing:`, which makes sense, as that module has been removed from `grails-core` here: grails/grails-core@e75bf0a3 and from the `grails-dependencies` here: grails/grails-core@7e2f4ff4

When removing that dependency in `build.gradle` the project builds without any issues, so it does not seem to be used anyway:
```groovy
  api "io.github.gpc:fields:$fieldsVersion"
  //testImplementation "org.grails:grails-plugin-testing"
```

**Comment by codeconsole** [comment]
@matrei what task are you running that results in an error? 

```
scaffolding % ./gradlew clean assemble

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 462ms
8 actionable tasks: 6 executed, 1 from cache, 1 up-to-date
WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
- The deprecated "gradleEnterprise.buildScan.tag" API has been replaced by "develocity.buildScan.tag"
- The deprecated "gradleEnterprise.buildScan.buildFinished" API has been replaced by "develocity.buildScan.buildFinished"
- The deprecated "gradleEnterprise.buildScan.background" API has been replaced by "develocity.buildScan.background"
- The deprecated "gradleEnterprise.server" API has been replaced by "develocity.server"
- The deprecated "gradleEnterprise.buildScan.publishIfAuthenticated" API has been replaced by "develocity.buildScan.publishing.onlyIf { it.authenticated }"
- The deprecated "gradleEnterprise.buildScan.uploadInBackground" API has been replaced by "develocity.buildScan.uploadInBackground"
- The deprecated "gradleEnterprise.buildScan.capture.taskInputFiles" API has been replaced by "develocity.buildScan.capture.fileFingerprints"
- The "com.gradle.enterprise" plugin has been replaced by "com.gradle.develocity"
- The "buildScan.publishAlways" API has been removed, the updated Develocity "buildScan.publishing" API publishes a Build Scan by default
scaffolding % java -version
openjdk version "11.0.22" 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-11.0.22.7.1 (build 11.0.22+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.22.7.1 (build 11.0.22+7-LTS, mixed mode)
```

**Comment by matrei** [comment]
@codeconsole It was actually only when loading the project in Intellij that the problem arose. Building from the command line ignores the problem.

After looking a little closer, I see that there aren't even any tests in this project.

So this belongs in it's own issue:
```console
~\Projects\grails\scaffolding git:[5.0.x]
./gradlew dI --dependency org.grails:grails-plugin-testing --configuration testCompileClasspath

> Task :dependencyInsight
org.grails:grails-plugin-testing: FAILED
   Failures:
      - Could not find org.grails:grails-plugin-testing:.

org.grails:grails-plugin-testing FAILED
\--- testCompileClasspath

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```

**Comment by matrei** [comment]
@codeconsole I created issue #111 and pr #112 as I didn't think this change belonged in this pr.

**Comment by codeconsole** [comment]
@matrei sorry, I didn't see that. I rolled back my removal commit and force pushed the pull request back to it's original state.

**Pull request merged**
